/*
 All Parts
 Additional unique keys generated by sequence and hash
 */
{{ config(always_create_constraint = true) }}

SELECT
    P.*,
    {% if target.type == 'snowflake' %}
    ['Test value']::ARRAY AS TEST_ARRAY_COL,
    {'Test key': 'Test value'}::OBJECT AS TEST_OBJECT_COL,
    {'Test key': 'Test value'}::VARIANT AS TEST_VARIANT_COL,
    {% else %}
    'Test value' AS TEST_ARRAY_COL,
    'Test value' AS TEST_OBJECT_COL,
    'Test value' AS TEST_VARIANT_COL,
    {% endif %}
    P.p_partkey AS "TitleCasePartKey",
    DENSE_RANK() over (order by p_partkey) as p_partkey_seq
FROM {{ ref('part') }} P
